apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-stromae
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-stromae
  template:
    metadata:
      labels:
        app: multi-stromae
    spec:
      containers:
        - name: multi-stromae
          image: laurentc35/multi-stromae:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
