apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: multi-stromae
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - multi-stromae.dev.insee.io
  rules:
    - host: multi-stromae.dev.insee.io
      http:
        paths:
          - path: /
            backend:
              serviceName: multi-stromae
              servicePort: http
