name: Build Docker Image and Deploy to image to DockerHub

on:
  push:
    branches:
      - main

jobs:
  multibuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone sources
        run: |
          chmod +x ./scripts/multi-clone.sh
          ./scripts/multi-clone.sh
        shell: bash
      - name: Multi build using Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          chmod +x ./scripts/multi-build.sh
          ./scripts/multi-build.sh
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source
        run: |
          git clone https://github.com/InseeFr/Stromae.git --branch v2-master --single-branch .
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn
      - run: yarn build
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download build
        id: download
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: laurentc35/multi-stromae
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
