name: Build Docker Image and Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source
        run: |
          git clone https://github.com/InseeFr/Stromae.git --branch v2-master --single-branch .
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn
      - run: yarn build
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
  heroku:
    needs: build
    name: Docker Build and deploy App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download build
        id: download
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Build and push Docker to Heroku
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          DOCKER_OPTIONS: "--no-cache"
        run: |
          echo ${HEROKU_API_KEY} | docker login \
            --username=${HEROKU_EMAIL} \
            registry.heroku.com \
            --password-stdin
          docker build \
            ${DOCKER_OPTIONS} \
            --tag registry.heroku.com/${HEROKU_APP_NAME}/web .
          heroku container:push web --app ${HEROKU_APP_NAME}
          heroku container:release web --app ${HEROKU_APP_NAME}
